default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: connect4_development

  host: <%= ENV["connect4_DB_DEV_HOST"] %>
  port: <%= ENV["connect4_DB_DEV_PORT"] %>
  username: <%= ENV["connect4_DB_DEV_USER"] %>
  password: <%= ENV["connect4_DB_DEV_PASS"] %>

test:
  <<: *default
  database: connect4_test

  host: <%= ENV["connect4_DB_DEV_HOST"] %>
  port: <%= ENV["connect4_DB_DEV_PORT"] %>
  username: <%= ENV["connect4_DB_DEV_USER"] %>
  password: <%= ENV["connect4_DB_DEV_PASS"] %>

production:
  <<: *default
  database: connect4_production
  username: connect4
  password: <%= ENV["connect4_DATABASE_PASSWORD"] %>